version: '3.2'

services:

  mongodb:
    image: mongo:latest
    container_name: challenge-mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: challenge-db
    ports:
      - 27017:27017