logging:
  file:
    name: /logs/challegenge-ms

spring:
  main:
    banner-mode: off
  data:
    mongodb:
      auto-index-creation: false
      database: challenge-db
      username: backend
      password: secret
      host: localhost
      port: 27017
      authentication-database: admin
  application:
    name: challegenge-ms

app:
  star-wars-api:
    base-url: https://swapi.dev/api
    resources:
      planets: /planets/1/
