server:
  port: 8080

logging:
  file:
    name: /logs/star-wars-ms

spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      auto-index-creation: false
      database: star-wars-db
      uri: mongodb://backend:secret@localhost:27017/admin
  application:
    name: star-wars-ms
  profiles:
    active: dev

app:
  star-wars-api:
    base-url: https://swapi.dev/api
    resources:
      planets: /planets/
